apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: built-image
      type: image
  params:
    - name: imageTag
      description: Tag to apply to the built image
  tasks:
  - name: source-to-image
    taskRef:
      name: source-to-image
    params:
      - name: pathToContext
        value: src
      - name: imageTag
        value: "${params.imageTag}"
    resources:
      inputs:
        - name: git-source
          resource: git-source
      outputs:
        - name: built-image
          resource: image
  - name: deploy-to-cluster
    taskRef:
      name: deploy-using-kubectl
    resources:
      inputs:
        - name: built-image
          resource: image
          from:
            - source-to-image