apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: picalc
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          serviceAccountName: build-bot
          container:
            image: __IMAGE__
